version: '3'
services:
  frontend:
    build:
      context: ./src/frontend
    ports:
      - "4000:4000"
    env_file:
      - src/frontend/.env
    depends_on:
      - backend
  backend:
    build: 
      context: ./src/backend
    ports:
      - "3000:3000"
    env_file:
      - src/backend/.env
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis
    ports:
      - "6379:6379"